## Welcome to NUMPY

In [4]:
import numpy as np

In [3]:
myarr = np.array([[3, 6, 37 ,7]], np.int64)


In [5]:
myarr[0,1]

6

In [7]:
myarr.shape

(1, 4)

In [8]:
myarr.dtype

dtype('int64')

In [10]:
myarr[0,1]=45

In [11]:
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

**Array Creation: Conversion from other python structures

In [13]:
listarr = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])

In [14]:
listarr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
listarr.dtype


dtype('int32')

In [16]:
listarr.shape

(3, 3)

In [17]:
listarr.size

9

In [18]:
np.array({34, 23 ,23})

array({34, 23}, dtype=object)

In [20]:
zeros = np.zeros((2,5))

In [21]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
 zeros.dtype

dtype('float64')

In [23]:
zeros.shape

(2, 5)

In [25]:
rng = np.arange(15)

In [26]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
lspace = np.linspace(1, 4, 4)

In [32]:
lspace

array([1., 2., 3., 4.])

In [34]:
emp = np.empty((4,6))

In [35]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511018e-306, 1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [6.23037317e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 3.56036603e-307, 1.37961641e-306],
       [1.37961302e-306, 1.11259940e-306, 1.60219035e-306,
        1.11261570e-306, 1.06811354e-306, 8.34448533e-308]])

In [36]:
emp_like = np.empty_like(lspace)

In [37]:
emp_like

array([1., 2., 3., 4.])

In [38]:
ide = np.identity(45)

In [39]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [40]:
ide.shape

(45, 45)

In [93]:
arr = np.arange(99)

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [96]:
arr =arr.reshape(3,33)

In [97]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [98]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [99]:
arr = arr.ravel()

In [100]:
arr.shape

(99,)

In [101]:
x =[[1, 2,3] , [4,5,6], [7, 1, 0]] 

In [102]:
ar = np.array(x)

In [103]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [105]:
ar.sum(axis=0)

array([12,  8,  9])

In [106]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [107]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [108]:
arr.flat

In [111]:
for item in ar.flat:
   print(item)

1
2
3
4
5
6
7
1
0


In [112]:
ar.ndim

2

In [113]:
ar.size

9

In [114]:
ar.nbytes


36

In [115]:

one = np.array([1,3, 4, 634,2])

In [116]:
one.argmax()

3

In [117]:
one.argmin()

0

In [118]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [119]:
ar.argmin()

8

In [120]:
ar.argmax()

6

In [121]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [122]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [123]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [124]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [126]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [127]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [128]:
ar2= np.array([[1, 7, 3],
       [1, 8, 6],
       [9, 1, 5]])

In [129]:
ar+ar2

array([[ 2,  9,  6],
       [ 5, 13, 12],
       [16,  2,  5]])

In [130]:
[32 , 43] + [56 ,90]

[32, 43, 56, 90]

In [132]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [133]:
ar2

array([[1, 7, 3],
       [1, 8, 6],
       [9, 1, 5]])

In [131]:
ar * ar2

array([[ 1, 14,  9],
       [ 4, 40, 36],
       [63,  1,  0]])

In [134]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [135]:
ar.max()

7

In [136]:
ar.min()

0

In [137]:
ar.sum()

29

In [138]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [139]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [140]:
np.count_nonzero(ar)

8

In [142]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [143]:
import sys

In [144]:
py_ar = [0, 4, 55,2]

In [148]:
np_ar = np.array(py_ar)


In [146]:
sys.getsizeof(1) * len(py_ar)

112

In [149]:
np_ar.itemsize * np_ar.size

16

In [150]:
np_ar.tolist()

[0, 4, 55, 2]